### ISSUE TITLE
TransparentConfig functionality

### ISSUE THREAD

**Issue by ghost** [tongtianxing/windows_ocxdemo#1]
Resolved

**Comment by 1MALKAVIAN** [comment]
I solved it by invoking `Program.form1.axCMSV6OCX1.GetDevNetFlowStatistics(szDevIDNO);`
before `long lRet = Program.Mainform.axCMSV6OCX1.TransparentConfig(szDevIDNO, 0, m_strParam, m_strParam.Length);` was called.

seems to be that the **Net Flow Statistics** must be called first before any parameter can be set.
